package cliutil

import (
	"flag"
	"fmt"
	"sort"
	"strings"
)

// FlagNames returns the long-flag spellings (--name) registered on fs, sorted.
// Completion scripts are generated FROM THE LIVE FlagSet so they can never
// drift from the binary's real flags.
func FlagNames(fs *flag.FlagSet) []string {
	var names []string
	fs.VisitAll(func(f *flag.Flag) {
		names = append(names, "--"+f.Name)
	})
	sort.Strings(names)
	return names
}

// BashCompletion returns a static bash completion script for bin, offering
// its subcommands in the first position and its flags everywhere.
func BashCompletion(bin string, subcommands []string, fs *flag.FlagSet) string {
	flags := strings.Join(FlagNames(fs), " ")
	subs := strings.Join(subcommands, " ")
	fn := "_" + strings.ReplaceAll(bin, "-", "_") + "_complete"
	return fmt.Sprintf(`# bash completion for %[1]s — GENERATED by `+"`%[1]s completion bash`"+`; do not edit.
# Install:  %[1]s completion bash > /etc/bash_completion.d/%[1]s
#      or:  source <(%[1]s completion bash)
%[2]s() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local subs="%[3]s"
    local flags="%[4]s"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$subs $flags" -- "$cur") )
    else
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
    fi
}
complete -o default -F %[2]s %[1]s
`, bin, fn, subs, flags)
}

// ZshCompletion returns a static zsh completion script for bin (a simple
// word-list completer: subcommands in position one, flags everywhere).
func ZshCompletion(bin string, subcommands []string, fs *flag.FlagSet) string {
	flags := strings.Join(FlagNames(fs), " ")
	subs := strings.Join(subcommands, " ")
	fn := "_" + strings.ReplaceAll(bin, "-", "_")
	return fmt.Sprintf(`#compdef %[1]s
# zsh completion for %[1]s — GENERATED by `+"`%[1]s completion zsh`"+`; do not edit.
# Install: place this file as %[2]s somewhere in your $fpath, e.g.
#   %[1]s completion zsh > "${fpath[1]}/%[2]s"
%[2]s() {
    local -a subs flags
    subs=(%[3]s)
    flags=(%[4]s)
    if (( CURRENT == 2 )); then
        compadd -- $subs $flags
    else
        compadd -- $flags
    fi
}
%[2]s "$@"
`, bin, fn, subs, flags)
}

// Completion dispatches `completion bash|zsh` and returns the script, or an
// error naming the accepted shells.
func Completion(shell, bin string, subcommands []string, fs *flag.FlagSet) (string, error) {
	switch shell {
	case "bash":
		return BashCompletion(bin, subcommands, fs), nil
	case "zsh":
		return ZshCompletion(bin, subcommands, fs), nil
	}
	return "", fmt.Errorf("unknown shell %q (want: %s completion bash|zsh)", shell, bin)
}
